import sqlite3

#Crear conexión
#conexion = sqlite3.connect("mibase.db")


#Crear puntero
#cursor = conexion.cursor()


#Se crea una tabla de categorias para mi base de datos

"""cursor.execute('''
CREATE TABLE CATEGORIAS(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
NOMBRE TEXT NOT NULL)''')"""


"""categorias = [
    (1, "Electro"),
    (2, "Hogar y textil"),
    (3, "Tiempo Libre"),
    (4,	"Bebés y Niños"),
    (5,	"Almacén"),
    (6,	"Bebidas"),
    (7,	"Frutas y Verduras"),
    (8,	"Carnes"),
    (9, "Pescados y Mariscos"),
    (10, "Quesos y Fiambres"),
    (11, "Lácteos"),
    (12, "Congelados"),
    (13, "Panadería y Repostería"),
    (14, "Perfumería"),
    (15, "Limpieza"),
    (16, "Mascotas") ]"""

#Inserto datos a la tabla categorias
#cursor.executemany("INSERT INTO CATEGORIAS VALUES (?, ?)", categorias)

#Crear una tabla de productos para mi base de datos

"""cursor.execute('''
CREATE TABLE PRODUCTOS(
"Nombre" TEXT NOT NULL,
"IdCategoria" INTEGER NOT NULL,
FOREIGN KEY("IdCategoria") REFERENCES "CATEGORIAS"("ID"))''')"""

"""productos = [

("Aire Acondicionado", 1),
("Ventilador", 1),
("Equipo de Audio", 1),
("Calefón",	1),
("Caloventor", 1),
("Estufa", 1),
("Microondas", 1),
("Horno", 1),
("Anafe", 1),
("Consola de Video Juegos", 1),
("Heladera", 1),
("Freezer", 1),
("Mouse", 1),
("Teclado", 1),
("Impresora", 1),
("PC Escritorio", 1),
("Notebook", 1),
("Tablet", 1),
("Celular", 1),
("Teléfono Fijo", 1),
("TV", 1),
("DVD", 1),
("Blu Ray", 1),
("Lavarropas", 1),
("Secarropas", 1),
("Pava Eléctica", 1),
("Cafetera", 1),
("Licuadora", 1),
("Plancha", 1),
("Batidora", 1),
("Toalla", 2),
("Toallón", 2),
("Repasador", 2),
("Delantal", 2),
("Colchón", 2),
("Almohada", 2),
("Alfombra", 2),
("Mantel", 2),
("Acolchado", 2),
("Frazada", 2),
("Sábanas", 2),
("Cubiertos", 2),
("Vaso", 2),
("Taza", 2),
("Mesa", 2),
("Silla", 2),
("Tablón", 2),
("Caballetes", 2),
("Mesa de Luz", 2),
("Lámpara", 2),
("Ténder", 2),
("Tabla de Planchar", 2),
("Cesto de Basura", 2),
("Contina de Baño", 2),
("Jabonera", 2),
("Bicicleta", 3),
("Corta Cesped", 3),
("Parrilla", 3),
("Reposera", 3),
("Sombrilla", 3),
("Gacebo", 3),
("Libro", 3),
("Cuaderno", 3),
("Resma", 3),
("Cartuchera", 3),
("Carpeta", 3),
("Tijera", 3),
("Lapicera", 3),
("Mochila", 3),
("Valija", 3),
("Pañales", 4),
("Mamadera", 4),
("Chupete", 4),
("Babero", 4),
("Juguete", 4),
("Cochecito", 4),
("Sillita", 4),
("Bañadera", 4),
("Cambiador", 4),
("Ropa", 4),
("Aceite", 5),
("Vinagre", 5),
("Aderezo", 5),
("Arroz", 5),
("Porotos", 5),
("Garbanzos", 5),
("Lentejas", 5),
("Caldo", 5),
("Sopa", 5),
("Puré", 5),
("Azucar", 5),
("Edulcorante",	5),
("Cacao", 5),
("Café", 5),
("Cereal", 5),
("Galletas Dulces", 5),
("Galletas Saladas", 5),
("Leche", 5),
("Mermelada", 5),
("Yerba", 5),
("Té", 5),
("Bizcochuelo", 5),
("Alfajores", 5),
("Caramelos", 5),
("Chocolates", 5),
("Harina", 5),
("Avena", 5),
("Pan Integral", 5),
("Pan de Salvado", 5),
("Pan Lactal", 5),
("Pan Rallado", 5),
("Tostadas", 5),
("Sal", 5),
("Pimienta", 5),
("Fideos", 5),
("Snacks", 5),
("Agua", 6),
("Cerveza", 6),
("Champagne", 6),
("Energizante", 6),
("Gaseosa", 6),
("Jugo en Polvo", 6),
("Jugo", 6),
("Licor", 6),
("Sidra", 6),
("Vino", 6),
("Whisky", 6),
("Fernet", 6),
("Naranja", 7),
("Pera", 7),
("Manzana", 7),
("Kiwi", 7),
("Mandarina", 7),
("Banana", 7),
("Uva", 7),
("Pomelo", 7),
("Ananá", 7),
("Limón", 7),
("Durazno", 7),
("Frutilla", 7),
("Zanahoria", 7),
("Zapallo", 7),
("Berenjena", 7),
("Ajo", 7),
("Choclo", 7),
("Camote", 7),
("Pimiento", 7),
("Tomate", 7),
("Papa", 7),
("Lechuga",	7),
("Cebolla", 7),
("Acelga", 7),
("Espinaca", 7),
("Repollo", 7),
("Brócoli", 7),
("Lomo", 8),
("Nalga", 8),
("Ojo de Bife",	8),
("Colita de Cuadril", 8),
("Peceto", 8),
("Paleta", 8),
("Bife de Chorizo",	8),
("Vacío", 8),
("Matambre", 8),
("Entraña", 8),
("Tapa de Asado", 8),
("Cuadrada", 8),
("Carré de Cerdo", 8),
("Pechito de Cerdo", 8),
("Matambre de Cerdo", 8),
("Bondiola de Cerdo", 8),
("Panceta", 8),
("Chorizo", 8),
("Morcilla", 8),
("Salchicha", 8),
("Suprema de Pollo", 8),
("Pata Muslo", 8),
("Pollo", 8),
("Filet de Merluza", 9),
("Filet de Salmón", 9),
("Atún", 9),
("Caballa", 9),
("Langostinos",	9),
("Camarones", 9),
("Calamar", 9),
("Queso Barra", 10),
("Queso Cremoso", 10),
("Queso Rallado", 10),
("Queso Untable", 10),
("Queso Azul", 10),
("Queso Mozzarella", 10),
("Jamón Cocido", 10),
("Salamín", 10),
("Bondiola", 10),
("Jamón Crudo", 10),
("Mortadela", 10),
("Aceitunas", 10),
("Crema", 11),
("Dulce de Leche", 11),
("Leche", 11),
("Manteca",	11),
("Postres", 11),
("Yogurt", 11),
("Margarina", 11),
("Hamburguesas", 12),
("Milanesas de Pollo", 12),
("Milanesas de Carne", 12),
("Helado", 12),
("Papas Fritas", 12),
("Pizza", 12),
("Pan", 13),
("Pre-Pizza", 13),
("Grisines", 13),
("Pan de Hamburguesa", 13),
("Pan de Pancho", 13),
("Shampoo", 14),
("Acondicionador", 14),
("Tintura", 14),
("Dentífrico", 14),
("Cepillo de Dientes", 14),
("Enjuague Bucal", 14),
("Hilo Dental", 14),
("Esponja", 14),
("Anti-Transpirante", 14),
("Jabón de Tocador", 14),
("Afeitadora", 14),
("Espuma de Afeitar", 14),
("Crema Corporal", 14),
("Crema Facial", 14),
("Algodón", 14),
("Alcohol", 14),
("Preservativos", 14),
("Curitas", 14),
("Toallitas Femeninas", 14),
("Quita Esmalte", 14),
("Esmalte de Uñas", 14),
("Lápiz Labial", 14),
("Delineador", 14),
("Balde", 15),
("Mopa", 15),
("Bolsa", 15),
("Escoba", 15),
("Guantes", 15),
("Pala", 15),
("Jabón en Pan", 15),
("Quitamanchas", 15),
("Suavizante", 15),
("Ambiental", 15),
("Desinfectante", 15),
("Insecticida",	15),
("Lavandina", 15),
("Detergente", 15),
("Antigrasa", 15),
("Limpia Vidrios", 15),
("Fósforos", 15),
("Escarbadientes", 15),
("Papel Higiénico", 15),
("Rollo de Cocina",	15),
("Pañuelos", 15),
("Trapo de Piso", 15),
("Secador de Piso",	15),
("Lustramuebles", 15),
("Limpiador de Piso", 15),
("Cera", 15),
("Alimento de Perro", 16),
("Alimento de Gato", 16),
("Juguetes", 16),
("Comida de Aves", 16),
("Comederos", 16),
("Collar", 16),
("Casita de Perro", 16),
("Camita", 16)

]"""

"""cursor.execute('''
CREATE TABLE LISTA(
PRODUCTO TEXT NOT NULL UNIQUE,
MARCA TEXT,
PRECIO INTEGER,
CANTIDAD INTEGER)''')"""

#Se insertan datos a la tabla productos

#cursor.executemany("INSERT INTO PRODUCTOS VALUES (?, ?)", productos)

#Se actualiza las operaciones para la base de datos
#conexion.commit()

#Se cierra la conexión
#conexion.close()